import { type NextPage } from "next";
import Head from "next/head";
import MeSection from "~/components/me_section/me_section";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <MeSection />
      </div>
    </>
  );
};

export default Home;
