import { type NextPage } from "next";
import Head from "next/head";
import MeSection from "~/components/me_section/me_section";
import Testimonials from "~/components/work_for_t/testimonials";
import WorkFor from "~/components/work_for_t/work_for";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto md:mt-5">
        <div className="justify-center gap-2 space-y-2 lg:flex xl:flex">
          <MeSection />
          <div className="md:space-y-4 ">
            <WorkFor
              company={[
                {
                  name: "Action Tokens",
                  logoUrl: "/images/logos/action-tokens.png",
                },
                {
                  name: "Action Tokens",
                  logoUrl: "/images/logos/action-tokens.png",
                },
              ]}
            />
            <Testimonials
              testis={[
                {
                  fullName: "A person",
                  imgUrl: "/images/logos/action-tokens.png",
                  position: "Director, x",
                  text: "Nice Nice nice nice nice Nice Nice nice nice nice Nice Nice nice nice nice Nice Nice nice nice nice",
                },
                {
                  fullName: "A person",
                  imgUrl: "/images/logos/action-tokens.png",
                  position: "Director, x",
                  text: "Nice Nice nice nice nice Nice Nice nice nice nice Nice Nice nice nice nice Nice Nice nice nice nice",
                },
                {
                  fullName: "A person",
                  imgUrl: "/images/logos/action-tokens.png",
                  position: "Director, x",
                  text: "Nice Nice nice nice nice Nice Nice nice nice nice Nice Nice nice nice nice Nice Nice nice nice nice",
                },
              ]}
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
